import type { Metadata } from "next"

import {
  DashboardMain,
  EmptyState,
  PageHeading,
} from "@/components/dashboard/ui"
import { requirePageRole } from "@/lib/auth/page-guards"

export const metadata: Metadata = { title: "Notifications · EMS" }

export default async function NotificationsPage() {
  await requirePageRole("owner", "supervisor")

  return (
    <DashboardMain className="gap-5">
      <PageHeading
        eyebrow="Account"
        title="Notifications"
        subtitle="Check-ins, late arrivals and blocked work, as they happen."
      />
      <EmptyState message="Nothing yet. Notifications are generated by check-in events, which arrive with the task store." />
    </DashboardMain>
  )
}
